version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 578813437933.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t tricity1 .
      - docker tag tricity1:latest 578813437933.dkr.ecr.us-east-1.amazonaws.com/tricity1:latest

      # Run Trivy with JSON output and store the report locally
      - docker run --rm -v $(pwd):/workdir aquasec/trivy:latest image tricity1:latest --format json -o /workdir/trivy-report.json

      # Convert JSON report to HTML
      - docker run --rm -v $(pwd):/workdir aquasec/trivy:latest convert --format html -o /workdir/trivy-report.html --input /workdir/trivy-report.json

      # Upload the HTML report to S3
      - aws s3 cp /workdir/trivy-report.html s3://pipelinezapout/

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 578813437933.dkr.ecr.us-east-1.amazonaws.com/tricity1:latest

artifacts:
  files: /workdir/trivy-report.html
